FROM php:7-cli-alpine
RUN apk --no-cache add git pcre-dev ${PHPIZE_DEPS} \ 
  && pecl install xdebug \
  && docker-php-ext-enable xdebug \
  && apk del pcre-dev ${PHPIZE_DEPS}
COPY --from=composer /usr/bin/composer /usr/bin/composer
WORKDIR /app